# Generated by Django 5.1.7 on 2025-04-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate in %",
                        max_digits=5,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_history",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
